import "./globals.css";
import { Josefin_Sans } from "next/font/google";

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="ja">
			<body className={josefinSans.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
